# Commande pour construire l'image Docker
build:
	docker build -t house-price-predictor .

# Commande pour exécuter le conteneur Docker
run:
	docker run -p 5000:5000 house-price-predictor

# Commande pour nettoyer les images et conteneurs Docker
clean:
	docker system prune -f

